#!/bin/sh
# Arch linux regular maintenance script
# run it manually and read the output thoroughly

# if outputting to a terminal, use COLORS
if [ -t 1 ]; then
  red() {
    tput setaf 1
  }
  green() {
    tput setaf 2
  }
  white() {
    tput setaf 7
  }
else
  red() {
    return
  }
  green() {
    return
  }
  white() {
    return
  }
fi

mirrorlist_settings="$@"
if [ -z "$mirrorlist_settings" ]; then
  mirrorlist_settings="--protocol https --sort score"
fi

echo -n Testing internet connection...
if (curl -s www.archlinux.org > /dev/null); then
  has_internet="yes"
  green
  echo OK
  white
else
  red
  echo FAILED
  white
  echo "  maintenance tasks requiring internet connectivity have been disabled"
  echo
fi

if (which reflector > /dev/null) && [ "$has_internet" ]; then
  echo -n Updating the pacman mirror list...
  if (reflector $mirrorlist_settings --sort score --save /tmp/mirrorlist); then
    sudo cp /tmp/mirrorlist /etc/pacman.d/mirrorlist
    green
    echo OK
    white
  else
    red
    echo FAILED
    white
    exit 1
  fi
fi

if [ "$has_internet" ]; then
  echo Upgrading the system...
  sudo pacman -Syuq 2>&1 | while read line; do
    echo "  $line"
  done
  echo
fi

echo Cleaning the pacman cache...
sudo paccache -r 2>&1 | while read line; do
  echo "  $line"
done
sudo paccache -ruk0 2>&1 | while read line; do
  echo "  $line"
done
echo

echo -n Checking for broken symlinks...
FOUND=`sudo find / -type l -! -exec test -e {} \; -print 2> /dev/null | grep -ve "^/\(proc\|run\)"`
if [ -z "$FOUND" ]; then
  green
  echo OK
  white
else
  echo
  echo "$FOUND" | while read line; do
    echo -n "  - $line -> "
    red
    ls -l "$line" | rev | cut -d' ' -f1 | rev
    white
  done
fi
echo

echo Checking for high-profile errors...
sudo journalctl -p 0..3 -xn | while read line; do
  echo "  $line"
done
echo

echo Checking for failed systemd services...
systemctl --all --failed | while read line; do
  echo "  $line"
done
echo

which lostfiles > /dev/null
if [ "$?" ]; then
  echo The following files are not owned by any package and should be investigated:
  sudo lostfiles | while read line; do
    echo "  - $line"
  done
  echo
fi

echo The following official packages have been explicitly installed:

# get the packages that pacman claims have been "explicitly installed"
# this includes base and base-devel, which is problematic
explicit=`pacman -Qen | cut -d' ' -f1`

# get the members of base and base-devel
bases=`pacman -Sg base | cut -d' ' -f2-`
basedevels=`pacman -Sg base-devel | cut -d' ' -f2-`
grouped="$bases $basedevels"

# pull members of base and base-devel out of the "explicitly installed" list
for pkg in $grouped; do
  explicit=`echo $explicit | sed "s/\b$pkg\b//g"`
done

# print 'em
for pkg in $explicit; do
  echo "  - $pkg"
done
echo

echo The following unofficial packages have been explicitly installed:
pacman -Qem | cut -d' ' -f1 | while read line; do
  echo "  - $line"
done
echo

echo -n All clean.
if [ "$has_internet" ]; then
  green
  echo " :-)"
  white
else
  echo " You should run with an internet connection to upgrade the system and update the mirror list."
fi
exit 0
